### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by coma333ryu** [hellworld-io/nBaseball#2]
# TO-Do list
- [ ] About result information
  - [ ] To write a json file.
  - [ ] To insert and update DB (SQlite or something)
  - [ ] No result
- [ ] About SNS share function
  - [ ] twitter
  - [ ] facebook
- [ ] write Documents
